---
title: "The RStudio integrated development environment"
teaching: 35
exercises: 10
questions:
 - "What is an Integrated Development Environment (IDE) and how can it make data analysis easier?"
objectives: 
- "Demonstrate the main features of RStudio for reproducible data anlysis."
keypoints: 
- "IDEs such as RStudio make coding and data analysis easier and more reproducible."
source: Rmd
---

# Introduction
There are two technologies essential to efficient,reproducible workflows:
1. Integrated development environments (IDEs) and
2. Literate programming
This episode will describe the first of these with RStudio as its main example.  

The goal of an IDE is to make coding and data analysis easier. 
IDEs are often tailored to specific languages (or sets of languages) but there is a set of 
features which are common to all.  These features are: 

1. A project management system
2. Language interpreter (and/or compiler)
3. Debugger
4. Version control
5. Lots of other *little* things e.g. file manager, interactive language console, bash terminal,
  syntax highlighting, autocomplete...

> ## Some useful IDEs
>
> * For `R` there is [RStudio](https://www.rstudio.com/) and [RStudio cloud](https://rstudio.cloud)
> * For `Python` there is [PyCharm](https://www.jetbrains.com/pycharm/)
> * For general purpose there is [Visual Studio Code](https://code.visualstudio.com/) or [Sublime Text](https://www.sublimetext.com/). 
> * For data science applications [Jupyter Lab](http://jupyter.org/) project is powerful. 
> 
{: .callout}

This episode will familiarise you with all the main features of `RStudio cloud`. These (mostly) map to the features of the desktop application `RStudio local` which you may be familiar with. We will be demonstrating the following features:
2. organising analysis into `Projects`;
3. the panes for special features, such as keeping track of variables;
3. tools for writing and running R code;
5. finding and squashing bugs with the debugger. 
The big feature not covered will version control, this will be covered in [episode 4]({{ page.root }}{% link _episodes/05-version-control-RStudio.md %}).

To help you get to grips with the main features, a useful cheat-sheet can be found [here](https://rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf), and to learn about the many `RStudio cloud` features you should go to the online documentation [here](https://rstudio.cloud/learn). 

# Analysis is organised in Projects

`Projects` keep track of settings tied to a particular data analysis project. When starting a new project you will create a new `RStudio project`. If you want to continue working on something,  just open up the `RStudio project` you want to work on a new project, just open up that project and continue where you left off. 

In order open an existing project navigate to:
1. `RStudio cloud`: your projects will be listed under `Your Workspace`
2. `RStudio local`: the `[project_name].Rproj` file, either through RStudio (`File` > `Open Project...`) or through your system file manager

## Setting up RStudio projects

You should already have a project called `roar` but just in case you haven't, complete either one of the exercises below, depending on whether you're using `RStudio local/cloud`. 

> ## Create a new `RStudio cloud` project
> 1. Navigate to [rstudio.cloud](rstudio.cloud)
> 2. Navigate to the `Your Workspace` tab. 
> 3. Click `New Project`
> 4. Rename `Untitled Project` to `roar`. 
{: .challenge}

> ## Create a new `RStudio local` project
> 1. Open RStudio
> 2. Select `File` > `New Project` > `New Directory` > `New Project` 
> 3. `Directory name`: "roar"
> 4. `Create project as...`: Select a convenient directory
> 5. Select `Create Project`
{: .challenge}

You'll also need to install the required packages so please run the following: 

```r
list.of.packages <- c("tidyverse", "data.table", "knitr", "markdown", "rmarkdown")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
```

## RStudio layout can be customized

Before we tour Rstudio let's make sure we've all configured our session the same way. 

> ## Rstudio set up
> 1. Open `Tools` > `Global Options`
> 2. Select the `Pane Layout` tab.  
> 3. Configure your RStudio with the following layout: 
>     1. Bottom left: `Console` and `Terminal`
>     2. Top left: `Source`
>     3. Top right: `Environment`, `History`, `VCS`
>     4. Bottom right: `Files`, `Plots`, `Packages`, `Help`, `Viewer`
> 4. Select the `Terminal` tab. 
> 4. Under `New terminals open with:` select `Bash` (or `Git Bash`)
> 4. Select `OK`
{: .challenge}

There are lots of options in the `Global Options` and `Project Options` menus which allow you to customize your environment. Please spend five minutes browsing the headings to see what customizations are available. 

> ## Global vs Project properties. 
> Pane layout is a 'Global property', that is, it will persist across different RStudio sessions.  
> There are project specific properties in the `Tools` > `Project options...` menu. Please  
> familiarise yourself with both sets of options. 
{: .callout}

<!-- Now look at `Files` pane (bottom right). You should see: -->
<!-- 1. `project.Rproj` (might be called `roar.Rproj` on `RStudio local`.) -->
<!-- 2. `.Rhistory` -->

<!-- The `Rproj` is a text file which contains all of the project  -->
<!-- specific settings. To see how `Projects` can benefit you we'll create some files, close and reopen -->
<!-- the project.  -->

## Project files make analysis easier

One of the main benefits of `Projects` is that 

> ## Create a file, run, save, close and reopen
> 1. Select `File` > `New File` > `New R Script` 
> 2. Write out the following in the file (or just copy and paste!): 
> 2. ~~~
>    x <- rnorm(10)
>    
>    sum <- 0
>    
>    for(i in 1:length(x)){
>        sum <- sum + x[[i]]
>    }
>    
>    print(sum)    
>    ~~~
>    {: .language-r}
> 3. Save the file as `test.R`
> 4. `Source` the file so that it runs. 
> 5. Observe the creation of the `sum` and `x` variables in the `Enivronment` pane (top right)
> 6. Close and reopen RStudio (making sure to `save` your data on exit). Make sure you read the 
> message!
> 7. If RStudio doesn't open up to the same project, navigate to the project using the `Files` pane 
> and clicking on the `test_project.Rproj` file.
{: .challenge}

Now answer these questions: 

> ## History and data
> You should now have two new files in your project. 
> What is the `.RData` file?  Hint: clear objects from your `Environment` (the broom icon next to 
> `Import Dataset`), then click on `.RData`. 
> > ## Solution
> > The `.RData` contains all your data! i.e. variables, functions, dataframes etc. in your 
> > environment. 
> {: .solution}
> What does `.RHistory` file do? Hint: Just click on it. 
> > ## Solution
> > The `.RHistory` is a text file containing all your previous commands. 
> {: .solution}
{: .challenge}

> ## When things go wrong
> Sometimes your project session will become corrupted, or start doing unexpected things. 
> The first thing to try when debugging is to remove your `.RData` file  from the project and 
> and clear your environment. Then try doing whatever your trying to do again. 
> Very often the cause lies within a dodgy object in the saved environment. 
{: .callout}


# Specilized panes have useful features

Here are some other RStudio features which you should be aware of. The `Console` and `Files` panes,
you should be already familiar with. 

The `Terminal` is the same as the console but for the `bash` language, try typing `pwd` 
(`p`rint `w`orking `d`irectory) to see what it does. 

`Packages` shows a list of all the packages you have installed. 

`Help` is the help files for all installed packages. 

`Git` we'll go through later (shout if you don't have this!)

`Environment` and `History` are useful so we'll do those as questions: 

> ## Environment 
> The environment pane contains all the objects in your session, e.g. functions, variables, 
> dataframes etc. There is more than one environment however, the default one shown is the 
> `Global Environemt`.  Select the `package: datasets` environment.  What does it show?  What happens
> if you click on an object there? 
> > ## Solution
> > It shows all the objects in the base R package `datasets`. If you click on an object it 
> > opens the dataset. 
> {: .solution}
> Try loading an installed package e.g. by running `library(data.table)` in the console. 
> Now open that environment and click
> on a `Value` e.g. `chgroup` . What happens?
> > ## Solution
> > The code is printed in the console. 
> {: .solution}
{: .challenge}


> ## History
> The history pane shows you all the previous commands that have been run. 
> Run the following command in the console: 
> ~~~ 
> y <- rbeta(10, 1, 2)
> ~~~
> {: .language-r}
> Now use the History pane to transfer this (with one click) to the last line of `test.R`. 
> > ## Solution
> > Highlight the relevant line and then click `To Source`. 
> {: .solution}
{: .challenge}


# RStudio has tools for easy code writing and running

Two other great features are tab complete and multiline editing. 

> ## Tab complete
> To tab complete, try typing <kbd>r</kbd> in the `test.R` file on a new line. Now hit the tab key 
> (<kbd>Tab</kbd>) and you should see a list come up full of functions, datasets and packages all 
> starting with the letter <kbd>r</kbd>. 
{: .challenge}

> ## Multiline editing
> This is very  useful for repetitive code or text. 
> 1. Create 5 blank lines in `test.R`. 
> 2. Click your curser to the top of those lines. 
> 3. Hold down <kbd>Alt</kbd> and drag your curser down 5 lines. 
> 4. Type 'I love R'. 
> 5. You should see 5 lots of 'I love R'. 
{: .challenge}

# The debugger helps you find errors

When you've got to this point, please let your instructor
know as we'll go through the debugger together. 

> ## Further reading
> Mastering all the features of an IDE is time consuming but well worth it. 
> Check out RStudio tutorials by clicking [here](https://support.rstudio.com/hc/en-us/sections/200107586-Using-the-RStudio-IDE)
{: .callout}

